name: Validate MDX

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Validate MDX
      run: |
        npm install @mdx-js/mdx
        node --no-warning ./scripts/mdxCompiler.js $(git diff-tree --name-only --no-commit-id -r ${{ github.base_ref }}..HEAD -- '*.md' ':(exclude).github/*')
      env:
        FORCE_EXIT: 1

    - name: exit if error
      run: exit $?
