name: Validate MDX

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Get changed files
      id: get_changed_files
      run: |
        git diff --name-only ${{github.base_ref}}...HEAD -- '*.md' > changed-files.txt

    - name: Run mdx.js script
      env:
        FORCE_EXIT: 1
      run: |
        node ./script/mdxCompiler.js $(cat changed-files.txt)
      if: steps.get_changed_files.outputs.status == 0

    - name: Handle Errors
      run: |
        if [ $FORCE_EXIT -ne 0 ]; then
            echo "There were compilation errors"
            cat errors.txt
            exit 1
        else
            echo "All files were successfully compiled"
